// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package de.eventalizer.domain;

import de.eventalizer.domain.Benutzer;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Benutzer_Roo_Configurable {
    
    declare @type: Benutzer: @Configurable;
    
}
